### ISSUE TITLE
app.log  error, 导致数据丢失.

### ISSUE THREAD

**Issue by im-zhangxi** [lyswhut/lx-music-sync-server#12]
![)K_`HPDAUS58GYXZ@DTKU_L](https://user-images.githubusercontent.com/18593080/228501032-fd6f88b2-52de-40db-bbf3-a02d9c23a387.png)

**Comment by lyswhut** [comment]
这只是连接意外断开的错误，与数据丢失无关，

导致数据丢失问题有多种可能，可以检查快照文件，找到数据丢失事件发生时的快照创建时间，结合快照创建时间查看app.log、access.log、控制台输出日志（若使用PM2，历史输出日志保存在`~/.pm2/logs/`）分析丢失数据时发生了什么
