### ISSUE TITLE
连接码

### ISSUE THREAD

**Issue by hfhtsoft** [lyswhut/lx-music-sync-server#14]
使用这个同步，连接时提示输入“连接码”，这个连接码在哪里看到？

**Comment by hfhtsoft** [comment]
![Uploading 111111111111a.png…]()

**Comment by zqq12345** [comment]
>> config.js
users: [
    // 用户配置例子，有两种配置格式
     {
     name: '111111', // 用户名，必须，不能与其他用户名重复
     password: 'aaaaaaa', // 是连接密码，必须，不能与其他用户密码重复，若在外网，务必增加密码复杂度
    //   maxSnapshotNum: 10, // 可选，最大备份快照数
    //   'list.addMusicLocationType': 'top', // 可选，添加歌曲到我的列表时的方式 top | bottom，参考客户端的设置-列表设置-添加歌曲到我的列表时的方式
     },
  ],

把注释去了，就是aaaaaaa
