### ISSUE TITLE
首次连接输入连接码后出现，状态显示:expected http 101 response but was '401 unauthorized'

### ISSUE THREAD

**Issue by UntaggedRui** [lyswhut/lx-music-sync-server#16]
使用docker compose部署，映射了一些目录
```bash
$ cat docker-compose.yml
version: '3.3'
services:
    lx-music:
        ports:
            - '8006:9527'
        volumes:
                - './data/config.js:/server/config.js'
                - './data/syncdata:/server/data'
        image: 'lxmusic'
        networks:
                - mynet
networks:
        mynet:
                external: true
```
已经输入了config.js中配制的这个用户的密码，但是仍然显示unauthorized如何解决？
已经尝试将./data/syncdata中的内容删除后重新创建容器，还是一样的错误。

**Comment by UntaggedRui** [comment]
虽然已经解决，但是没明白为什么。。
我原来的nginx文件是这样的。
```conf
 location / { # 该规则用于代理路径下的http请求
                proxy_set_header X-Real-IP $remote_addr;  # 该头部与config.ts文件的 proxy.header 对应
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host  $http_host;
                proxy_set_header Connection "";
                proxy_set_header X-Nginx-Proxy true;
                proxy_pass http://127.0.0.1:8006;
                proxy_redirect default;
        }
```
我该成了这样的，就可以了。
```conf
	location /api/ { # 该规则用于代理路径下的http请求
    proxy_set_header X-Real-IP $remote_addr;  # 该头部与config.ts文件的 proxy.header 对应
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host  $http_host;
    proxy_set_header Connection "";
    proxy_set_header X-Nginx-Proxy true;
    proxy_pass http://127.0.0.1:8006;
    proxy_redirect default;
}
location /api { # 该规则用于代理路径下的ws请求
    proxy_set_header X-Real-IP $remote_addr; # 该头部与config.ts文件的 proxy.header 对应
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host  $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Nginx-Proxy true;
    proxy_pass http://127.0.0.1:8006;
    proxy_redirect default;
}
```
又是栽在了nginx的配置文件上。。。。

**Comment by lyswhut** [comment]
下面那个规则是代理web socket连接，也是必须的

**Comment by BenorX** [comment]
nginx反向代理之后可以访问/hello，但是用客户端连接会失败，nginx日志显示401

**Comment by BenorX** [comment]
> nginx反向代理之后可以访问/hello，但是用客户端连接会失败，nginx日志显示401
重新按照作者的配置后，可以正常nginx反向代理了，两个规则都需要配置，并且xxx后的斜杠一定要注意

**Comment by EvasiveBears** [comment]
主要是部署文档写的太他妈垃圾了，就写你妈个/xxx 和 /xxx/具体的api路径他妈的路径又不给出来，我怎么知道他妈的Nginx那个路径怎么填。跟他妈傻逼似的

**Comment by lyswhut** [comment]
首先，交流时请注意素质。
其次，你真看懂了这个配置的意思？这里的`xxx`是指由你自定义的前缀路径，只要是这个前缀的请求就转发到lx sync，为什么你会把`xxx`理解为lx sync内部的api路径呢？

**Comment by EvasiveBears** [comment]
> 首先，交流时请注意素质。 其次，你真看懂了这个配置的意思？这里的`xxx`是指由你自定义的前缀路径，只要是这个前缀的请求就转发到lx sync，为什么你会把`xxx`理解为lx sync内部的api路径呢？

首先，我承认我的素质不是很好，我想您道歉。因为当时部署这个服务器由于您的文档不同于常规的部署方式，让我浪费很多时间来部署，甚至还去看了ts语法，心里有些气不过，于是才有恰当的言论。一般nginx部署反代都是通过判断子域名来确定将请求转发到哪后端服务。有谁会根据同一域名的不同请求路径来转发请求？

**Comment by yizeijun** [comment]
> 同一子域下部署多个服务是很正常的事，文档也是按照这种方式去写的，如果不要前缀路径，那配置会类似下面的样子：
> 
> ```
> location = / {
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host  $http_host;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "Upgrade";
>     proxy_set_header X-Nginx-Proxy true;
>     proxy_pass http://127.0.0.1:9527;
>     proxy_redirect default;
> }
> location / {
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host  $http_host;
>     proxy_set_header Connection "";
>     proxy_set_header X-Nginx-Proxy true;
>     proxy_pass http://127.0.0.1:9527;
>     proxy_redirect default;
> }
> ```

博主你好，使用docker搭建成功用IP加端口号可以连接成功，但是使用反代的SSL就不行，根据你这个评论，我再宝塔面板的反代配置也完成同样的代码，此时/hello反馈正常，但是连接时仍然提示Unexpected server response: 401

**Comment by lyswhut** [comment]
v2.0.0及以上版本的Nginx配置改了，详情看Readme的例子

**Comment by kekeguai** [comment]
> v2.0.0及以上版本的Nginx配置改了，详情看Readme的例子

Nginx Proxy Manager 直接配置反向代理，软件提示401，修改反向代理配置 提示502

**Comment by ods-im** [comment]
群晖部署，使用的不是**Nginx  **，怎么解决这个问题呢？lxmusic.xxxxx.im/hello页面显示成功

**Comment by nalipiaoxiang** [comment]
确实是websocket的问题,nginx不会用的推荐使用nginxwebui,直接监听一个你想用的端口,配上证书,添加代理目标到http://192.168.x.x:9527,把websocket配上401就好了
![Uploading Snipaste_2024-04-20_22-25-21.png…]()
