### ISSUE TITLE
能不能支持ipv6啊。没有公网ip，只有ipv6，想给我的车机上的洛雪音乐也同步

### ISSUE THREAD

**Issue by ssh1171266849** [lyswhut/lx-music-sync-server#30]
能不能支持ipv6啊。没有公网ip，只有ipv6，想给我的车机上的洛雪音乐也同步

**Comment by helloplhm-qwq** [comment]
将配置的ip地址改成0.0.0.0试试？

**Comment by tuiseliunian** [comment]
docker run -d \
   --restart unless-stopped \
   --name lx-music-sync-server \
   -p 9527 :9527 \
   -v /volume1/docker/lx-music-sync-server/data:/server/data \
   -v /volume1/docker/lx-music-sync-server/logs:/server/logs \
   -e LX_USER_ossuser='!mypassword' \
   -e BIND_IP=:: \
   wbsu2003/lx-music-sync-server

添加如下环境变量即可：
-e BIND_IP=::

**Comment by ssh1171266849** [comment]
多谢
