### ISSUE TITLE
貌似要么只能ipv4要么ipv6，可否同时支持v4和v6呢

### ISSUE THREAD

**Issue by HyperLYP** [lyswhut/lx-music-sync-server#38]
如题

**Comment by lyswhut** [comment]
如果没有使用代理服务的话，则可以将 `BIND_IP` 设置为 `::` 后会同时支持ipv4和ipv6

**Comment by HyperLYP** [comment]
> 如果没有使用代理服务的话，则可以将 `BIND_IP` 设置为 `::` 后会同时支持ipv4和ipv6

好的好的，谢谢
