### ISSUE TITLE
无法监听外网地址

### ISSUE THREAD

**Issue by Kbstsn** [lyswhut/lx-music-sync-server#40]
我尝试修改了config.js和ecosystem.config.js这两个文件的IP，但始终监听的是127.0.0.1这个本地的9527端口。

**Comment by lyswhut** [comment]
改IP或端口绑定的话用环境变量或者改config.js，文件内有注释例子，改了的话启动时也会有日志输出

**Comment by Kbstsn** [comment]
> 
搞定了，原因是改了配置文件没有将PM2的程序删除再重启
