### ISSUE TITLE
docker部署server同步能正常，但有报错。

### ISSUE THREAD

**Issue by Haruter** [lyswhut/lx-music-sync-server#49]
docker logs上面每次同步都会有一条提升文件无法找到
`handleMergeListDataFromSnapshot
[2023-09-12T08:57:47.620] [WARN] sync - [Error: ENOENT: no such file or directory, open '/server/data/users/admin_21232f/dislike/snapshot/snapshot_d41d8cd98f00b204e9800998ecf8427e'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/server/data/users/admin_21232f/dislike/snapshot/snapshot_d41d8cd98f00b204e9800998ecf8427e'
}
getRemoteListData
handleSyncList remoteListData, localListData
localListData 0
remoteListData 0
[2023-09-12T08:57:47.736] [INFO] sync - status [ 'admin Dev', 'admin Xiaomi M2102J2SC' ]
handleListAction admin list_music_add
`
请问这个跟目录权限有关联吗？docker run 的时候是否需要添加pid?
这是我的运行命令
`docker run -d \
--name="lx-music" \
-p 19527:9527 \
-e BIND_IP="0.0.0.0" \
-e LX_USER_admin="password" \
-v /home/docker/lxmusic/config:/server/config \
-v /home/docker/lxmusic/data:/server/data \
-e CONFIG_PATH="/server/config" \
-e DATA_PATH="/server/data" \
--restart always \
lyswhut/lx-music-sync-server
`
映射的目录权限都是777的。

**Comment by lyswhut** [comment]
你有没有手动删除过data数据里面的内容呢？
你停止服务，手动去删掉`/server/data/users/admin_21232f/dislike`目录，再启用服务连接试试？

**Comment by lyswhut** [comment]
这个问题已在v2.0.3修复，只有服务端跟客户端的数据为空时才会触发这个问题，更新后删掉`/data/users/<用户名>/dislike`目录再启动即可
