### ISSUE TITLE
2.4.1客户端在最新版服务端登陆后401

### ISSUE THREAD

**Issue by nsnake** [lyswhut/lx-music-sync-server#51]
通git拉取代码后执行
docker build -t lx-music-sync-server，启动时只加了端口map。并修改了config.ts文件增加了用户名和密码
在2.4.1的客户端开启同步后提示输入对应密码，输入完后出现401错误。
可以确定密码是对的

**Comment by nsnake** [comment]
已解决，nginx配置修改了。
不过文档里面有个问题，如果直接使用可能会出现
nginx: [emerg] unknown "connection_upgrade" variable

需要在server前面加上如下内容：
```
map $http_upgrade $connection_upgrade{
    default upgrade;
    '' close;
  }
```

**Comment by lyswhut** [comment]
是的，文档漏了这个
