### ISSUE TITLE
更新同步服务后报错

### ISSUE THREAD

**Issue by ZGJRIJ** [lyswhut/lx-music-sync-server#57]
更新同步服务后报错
Load config: /opt/lx-music-sync-server/config.js
Users:
test: 123456

undefined:1

SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at /opt/lx-music-sync-server/server/user/data.js:62:34
at Array.map (<anonymous>)
at Object.<anonymous> (/opt/lx-music-sync-server/server/user/data.js:59:76)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)

Node.js v21.1.0

**Comment by ZGJRIJ** [comment]
删除data文件夹后启动了但还是有报错，不知道是不是正常的。

[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/lx-music-sync-server-error.log last 15 lines:
0|lx-music |     at Module.load (node:internal/modules/cjs/loader:1207:32)
0|lx-music |     at Module._load (node:internal/modules/cjs/loader:1023:12)
0|lx-music |     at Module.require (node:internal/modules/cjs/loader:1235:19)
0|lx-music |     at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
0|lx-music | SyntaxError: Unexpected end of JSON input
0|lx-music |     at JSON.parse (<anonymous>)
0|lx-music |     at /opt/lx-music-sync-server/server/user/data.js:62:34
0|lx-music |     at Array.map (<anonymous>)
0|lx-music |     at Object.<anonymous> (/opt/lx-music-sync-server/server/user/data.js:59:76)
0|lx-music |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
0|lx-music |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
0|lx-music |     at Module.load (node:internal/modules/cjs/loader:1207:32)
0|lx-music |     at Module._load (node:internal/modules/cjs/loader:1023:12)
0|lx-music |     at Module.require (node:internal/modules/cjs/loader:1235:19)
0|lx-music |     at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)

**Comment by lyswhut** [comment]
出于未知的原因，升级后你的数据损坏了，如果你升级前有备份data目录，可以在备份现有data目录后将其替换回去再次启动看能不能重现该问题，若可以的话你可以将数据打包发我邮箱看看

**Comment by ZGJRIJ** [comment]
> 出于未知的原因，升级后你的数据损坏了，如果你升级前有备份data目录，可以在备份现有data目录后将其替换回去再次启动看能不能重现该问题，若可以的话你可以将数据打包发我邮箱看看

http://123.60.165.66:7001/s/L1tm

**Comment by ZGJRIJ** [comment]
> 出于未知的原因，升级后你的数据损坏了，如果你升级前有备份data目录，可以在备份现有data目录后将其替换回去再次启动看能不能重现该问题，若可以的话你可以将数据打包发我邮箱看看

没找到你的邮箱

**Comment by ZGJRIJ** [comment]
> 出于未知的原因，升级后你的数据损坏了，如果你升级前有备份data目录，可以在备份现有data目录后将其替换回去再次启动看能不能重现该问题，若可以的话你可以将数据打包发我邮箱看看

文件已经发了

**Comment by lyswhut** [comment]
刚看了下，你发的数据是没有问题的啊，而且这是升级后的数据，我的意思是升级前的data目录你有备份吗？

**Comment by ZGJRIJ** [comment]
> 刚看了下，你发的数据是没有问题的啊，而且这是升级后的数据，我的意思是升级前的data目录你有备份吗？
> 
> > 删除data文件夹后启动了但还是有报错，不知道是不是正常的。
> 
> 这个是之前的日志，只要可以正常启动，那就没问题

那一份启动不了的发给你了

**Comment by lyswhut** [comment]
也仍然是没问题的：
![image](https://github.com/lyswhut/lx-music-sync-server/assets/20365169/06a87c51-495b-4437-af13-26b4f826a146)


而且这份数据也是升级后的数据

**Comment by ZGJRIJ** [comment]
> 也仍然是没问题的：
> ![image](https://github.com/lyswhut/lx-music-sync-server/assets/20365169/06a87c51-495b-4437-af13-26b4f826a146)
> 
> 
> 而且这份数据也是升级后的数据

那就不知道了，搞不清楚

**Comment by ZGJRIJ** [comment]
> 也仍然是没问题的：
> ![image](https://github.com/lyswhut/lx-music-sync-server/assets/20365169/06a87c51-495b-4437-af13-26b4f826a146)
> 
> 
> 而且这份数据也是升级后的数据

这个要先关闭吗？

**Comment by lyswhut** [comment]
你可以执行 `pm2 flush`，然后重启看看，你那些日志是历史错误日志

**Comment by ZGJRIJ** [comment]
> 你可以执行 `pm2 flush`，然后重启看看，你那些日志是历史错误日志

我试了一下，确实没有出现报错了

**Comment by ZGJRIJ** [comment]
> 你可以执行 `pm2 flush`，然后重启看看，你那些日志是历史错误日志

这个报告之前的错误是我没想到的

**Comment by lyswhut** [comment]
所以最终还是没能重现这个问题，不清楚是怎么情况下导致的文件异常

**Comment by ZGJRIJ** [comment]
> 所以最终还是没能重现这个问题，不清楚是怎么情况下导致的文件异常

这次没什么经验，没保存好文件，只能看下次，什么时候出现了。

**Comment by ZGJRIJ** [comment]
> 所以最终还是没能重现这个问题，不清楚是怎么情况下导致的文件异常

/root/.pm2/logs/lx-music-sync-server-error.log last 15 lines:
0|lx-music |     at Module.load (node:internal/modules/cjs/loader:1205:32)
0|lx-music |     at Module._load (node:internal/modules/cjs/loader:1021:12)
0|lx-music |     at Module.require (node:internal/modules/cjs/loader:1230:19)
0|lx-music |     at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
0|lx-music | SyntaxError: Unexpected end of JSON input
0|lx-music |     at JSON.parse (<anonymous>)
0|lx-music |     at /home/server/lx-music-sync-server/server/user/data.js:62:34
0|lx-music |     at Array.map (<anonymous>)
0|lx-music |     at Object.<anonymous> (/home/server/lx-music-sync-server/server/user/data.js:59:76)
0|lx-music |     at Module._compile (node:internal/modules/cjs/loader:1368:14)
0|lx-music |     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
0|lx-music |     at Module.load (node:internal/modules/cjs/loader:1205:32)
0|lx-music |     at Module._load (node:internal/modules/cjs/loader:1021:12)
0|lx-music |     at Module.require (node:internal/modules/cjs/loader:1230:19)
0|lx-music |     at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)

**Comment by ZGJRIJ** [comment]
> 所以最终还是没能重现这个问题，不清楚是怎么情况下导致的文件异常

data文件移掉就可以了
，文件要发给你吗？

**Comment by lyswhut** [comment]
升级前的数据？如果将数据放进去后启动服务能重现问题，可以发给我看看

**Comment by ZGJRIJ** [comment]
> 升级前的数据？如果将数据放进去后启动服务能重现问题，可以发给我看看

还有就是config文件要一起发吗？

**Comment by lyswhut** [comment]
不用，数据就行，打成压缩包

**Comment by ZGJRIJ** [comment]
> 不用，数据就行，打成压缩包

好的，我下午还要开会，稍微晚点发给你。

**Comment by ZGJRIJ** [comment]
> 不用，数据就行，打成压缩包

文件收到了吗？QQ邮箱

**Comment by lyswhut** [comment]
收到了，你数据问题有问题：
`users/zgj_15639b/devices.json`是空的，至于为什么变成了空就不清楚了
![image](https://github.com/lyswhut/lx-music-sync-server/assets/20365169/13a3adb8-4272-4a02-a693-152ca71a29d1)

**Comment by ZGJRIJ** [comment]
> 收到了，你数据问题有问题：
> `users/zgj_15639b/devices.json`是空的，至于为什么变成了空就不清楚了
> ![image](https://github.com/lyswhut/lx-music-sync-server/assets/20365169/13a3adb8-4272-4a02-a693-152ca71a29d1)
> 

所以问题这次的问题原因和上次还不一样是吗？

**Comment by lyswhut** [comment]
不清楚，上次你发的数据是没问题的，这次发的数据是有问题的，删掉devices.json试试，
你是做了什么导致出现的问题

**Comment by ZGJRIJ** [comment]
> 不清楚，上次你发的数据是没问题的，这次发的数据是有问题的，停止服务删掉devices.json再启动试试，
> 你是做了什么导致出现的问题

我也不记得了
