### ISSUE TITLE
config.js中如何设置可选环境变量？

### ISSUE THREAD

**Issue by Joackk** [lyswhut/lx-music-sync-server#7]
np2安装总是失败，所以就直接在config.js照着ecosystem.config.js 中的格式设置了下绑定IP和端口，但是不管怎么设置都没有生效，请问具体该在config.js中设置呢？
![image](https://user-images.githubusercontent.com/45162558/227822985-f2242c48-180e-425e-9677-508098404604.png)
![image](https://user-images.githubusercontent.com/45162558/227823028-cf27d8ce-c0b6-4224-ad15-5eaa36e634b7.png)

**Comment by lyswhut** [comment]
在v1.3.0添加了在配置文件读取环境变量的功能，详情看配置文件内的说明
