### ISSUE TITLE
使用域名来开启同步服务的问题

### ISSUE THREAD

**Issue by JuneDrinleng** [lyswhut/lx-music-sync-server#79]
大佬您好，我用nginx配置了我的公网ip:80端口转发到127.0.0.1:9527来实现lx music 同步服务的代理，同时我也在cloudfare上配置了一个域名指向我的公网ip，而且我直接访问我这个域名得到nginx代理成功的消息，说明dns解析应该没啥问题；同时我在lxmusic上尝试了公网ip：80也可以正确实现同步服务，那么问题就在于lxmusic 移动端可以配置ip但不能配置域名，我想知道是我的操作问题还是因为不支持域名的方式同步呢

**Comment by lyswhut** [comment]
PC、移动端都可以使用域名访问，按理说PC可以移动端也可以，可以清理日志后，勾选记录同步日志再启用同步看看输出什么日志

**Comment by JuneDrinleng** [comment]
> PC、移动端都可以使用域名访问，按理说PC可以移动端也可以，可以清理日志后，勾选记录同步日志再启用同步看看输出什么日志

我看了一下，我服务器阿里云的但域名是国外买的，没备案qwq
